name: Windows

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
      
      - name: Support longpaths
        run: git config --system core.longpaths true  # https://github.com/orgs/community/discussions/26952 
      
      - name: configure
        run: cmake -Stest -Bbuild --log-level=DEBUG

      - name: build
        run: cmake --build build --config Debug -j4 --verbose

      - name: test
        run: |
          cd build
          ctest --build-config Debug -j4
